import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'
import Footer from '../components/footer'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>BRANDNAME</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={styles.mainContainer}>
        <div className={styles.grid}>
          <div className={styles.child}>
            <h1>Generate ads in <span style={{ color: 'darkorange' }}>seconds</span> with AI</h1>
            <p style={{ color: 'grey' }}>Beautiful, eye catching and highly converting ads for all your marketing channels. No design or coding experience needed</p>
            <Link href={'/signup'}>
              <button className={styles.signupBtn}>
                <span>Sign up for early access</span>
              </button>
            </Link>
          </div>
          <div className={styles.child}>
            <Image
              src="/image.avif"
              width={800}
              height={800}
              alt="Picture of the author"
            />
          </div>
        </div>
        <div className={styles.subText}>
          <h3>Supports all your marketing channels</h3>
          <p>All marketing channels, ad formats, and sizes are supported</p>
        </div>
      </div>
      <div className={styles.container} style={{ marginTop: '-50px' }}>
        <h1>How it works</h1>
        <div className={styles.grid2}>
          <div>
            <Image
              src="/image2.avif"
              width={200}
              height={200}
              alt="Picture of the author"
              layout='fixed'
            />
            <h2>1. Select brand</h2>
            <p>Some random description text</p>
          </div>
          <div>
            <Image
              src="/image2.avif"
              width={200}
              height={200}
              alt="Picture of the author"
              layout='fixed'
            />
            <h2>2. Select brand</h2>
            <p>Some random description text</p>
          </div>
          <div>
            <Image
              src="/image2.avif"
              width={200}
              height={200}
              alt="Picture of the author"
              layout='fixed'
            />
            <h2>3. Select brand</h2>
            <p>Some random description text</p>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  )
}

export default Home
