import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'
import Footer from '../components/footer'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={styles.mainContainer}>
        <div className={styles.child}>
          <h1>Generate ads in <span style={{ color: 'darkorange' }}>seconds</span> with AI</h1>
          <p style={{ color: 'grey' }}>Beautiful, eye catching and highly converting ads for all your marketing channels. No design or coding experience needed</p>
          <button className={styles.signupBtn}>
            <span>Sign up for early access</span>
          </button>
        </div>
        <div className={styles.child}>
          <Image
            src="/image.avif"
            width={800}
            height={800}
          />
        </div>
      </div>
      <Footer />
    </div>
  )
}

export default Home
