import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Signup.module.css'
import Navbar from '../components/navbar'
import Footer from '../components/footer'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>BRANDNAME | Signup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={styles.mainContainer}>
        <div className={styles.signupWrapper}>
          <h1 className={styles.headline}>Sign up for early access</h1>
          <p
            style={{ color: 'grey' }}
            className={styles.subText}
          >Enter your email below and join the waitlist for BRANDNAME</p>
          <div className={styles.fields}>
            <input
              type="email"
              className={styles.emailInput}
              placeholder="Enter your email..."
            />
            <button className={styles.signupBtn}>
              <span>Sign up</span>
            </button>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  )
}

export default Home
